//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgentsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSale
    {
        public long ID { get; set; }
        public long ProductID { get; set; }
        public string ProductName { get; set; }
        public long AgentID { get; set; }
        public string AgentName { get; set; }
        public Nullable<System.DateTime> DateOfRelease { get; set; }
        public int CountOfProduct { get; set; }
    
        public virtual Agents Agents { get; set; }
        public virtual ProductsShort ProductsShort { get; set; }
    }
}
